### ISSUE TITLE
Plugin 'EclipseCodeFormatter' failed to initialize and will be disabled.  Please restart Android Studio.

### ISSUE THREAD

**Issue by if412031** [krasa/EclipseCodeFormatter#102]
Plugin 'EclipseCodeFormatter' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.ClassNotFoundException: krasa.formatter.settings.GlobalSettings PluginClassLoader[EclipseCodeFormatter, 15.6.132.637.1]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:274)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:408)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:197)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

why? I using android studio 2.1.2
I got this when install this plugin.

**Comment by krasa** [comment]
Corrupted download? Try to reinstall.

**Comment by if412031** [comment]
Not corrupted, I try to install from Android Studio 2.1.2 directly, it is still not working
the error is cannot open zip file

**Comment by if412031** [comment]
I have try to 2.1.1 and it works well
I think the problem is the plugin not compatible to 2.1.2
help me.

**Comment by krasa** [comment]
"the error is cannot open zip file"
what do you mean by that?

**Comment by if412031** [comment]
the android studio just give the 'cannot open zip file' warning.

and if I install manual from git, the error like the what I report before

**Comment by krasa** [comment]
What warning? What zip file? Please post the error so I can know what are you talking about.

Installed from repo, via gui....
![image](https://cloud.githubusercontent.com/assets/1160875/16154638/03a5f7d2-34ac-11e6-8f02-faa475c74507.png)


You know what, go to .AndroidStudio2.1\config\plugins\EclipseFormatter\lib, open EclipseFormatter.jar, and look whats in there
![image](https://cloud.githubusercontent.com/assets/1160875/16154752/84174470-34ac-11e6-95b9-6177217474ae.png)

**Comment by if412031** [comment]
![here](https://cloud.githubusercontent.com/assets/6178933/16154865/eb888964-34d6-11e6-9b4e-523f2f93a0d8.JPG)

**Comment by if412031** [comment]
Plugin 'EclipseCodeFormatter' failed to initialize and will be disabled. Please restart Android Studio.

java.lang.ClassNotFoundException: krasa.formatter.settings.GlobalSettings PluginClassLoader[EclipseCodeFormatter, 15.6.132.637.1]
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:274)
at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:408)
at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:197)
at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
at java.awt.EventQueue.access$300(EventQueue.java:103)
at java.awt.EventQueue$3.run(EventQueue.java:699)
at java.awt.EventQueue$3.run(EventQueue.java:697)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by krasa** [comment]
That's what you posted before, where's the zip file error?

**Comment by if412031** [comment]
yes, forget about that zip file error message

**Comment by if412031** [comment]
I don;t know why it happen.
Or there are some dependencies of the plugin?

**Comment by krasa** [comment]
just reinstall/redownload the plugin, and post me the log.

**Comment by if412031** [comment]
I got the solution. If I download the plugin from this git, I will get error like before, but if I download from https://plugins.jetbrains.com/plugin/6546, It works well
Thanks
