### ISSUE TITLE
IndexOutOfBoundsException with IDEA 2016.2

### ISSUE THREAD

**Issue by wuSam** [krasa/EclipseCodeFormatter#106]
Index: 5564, Size: 5549
java.lang.IndexOutOfBoundsException: Index: 5564, Size: 5549
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.eclipse.jdt.internal.formatter.TokenManager.get(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TokenManager.findFirstTokenInLine(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TokenManager.findFirstTokenInLine(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TextEditsBuilder.bufferIndent(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TextEditsBuilder.bufferWhitespaceBefore(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TextEditsBuilder.token(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TokenTraverser.traverse(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TokenManager.traverse(Unknown Source)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(Unknown Source)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(Unknown Source)
	at krasa.formatter.adapter.EclipseJavaFormatterAdapter45.format(EclipseJavaFormatterAdapter45.java:80)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.format(JavaCodeFormatterFacade.java:53)
	at krasa.formatter.plugin.EclipseCodeFormatter.reformat(EclipseCodeFormatter.java:112)
	at krasa.formatter.plugin.EclipseCodeFormatter.formatWhenEditorIsOpen(EclipseCodeFormatter.java:90)
	at krasa.formatter.plugin.EclipseCodeFormatter.format(EclipseCodeFormatter.java:55)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:221)
	at krasa.formatter.plugin.EclipseCodeStyleManager.format(EclipseCodeStyleManager.java:112)
	at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:75)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.b(ReformatCodeProcessor.java:131)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:905)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:332)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:406)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.b(AbstractLayoutCodeProcessor.java:403)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by wuSam** [comment]
ohhhh...there was a syntax error in my code. i forgot an closing ")". that's why this exception came

**Comment by krasa** [comment]
Eclipse bug, Nothing I can do.

**Comment by klaushauschild1984** [comment]
Maybe somebody could file a ticket at Eclipse bug tracking?

**Comment by krasa** [comment]
Definitely.

**Comment by markiewb** [comment]
Perhaps this issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=488642 ?

**Comment by krasa** [comment]
Perhaps.  We need to upgrade to 4.6, it is likely to be fixed. Lets close this.
