### ISSUE TITLE
Eclipse Import Optimizer failed

### ISSUE THREAD

**Issue by bbili** [krasa/EclipseCodeFormatter#108]
## intellij version
IntelliJ IDEA 2016.2
Build #IC-162.1121.32, built on July 9, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

## error:
Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
	at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:34)
	at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:15)
	at krasa.formatter.settings.provider.CachedProvider.get(CachedProvider.java:26)
	at krasa.formatter.plugin.EclipseImportOptimizer.getImportSorter(EclipseImportOptimizer.java:109)
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:60)
	at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:24)
	at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:48)
	at com.intellij.codeInsight.actions.OptimizeImportsProcessor.lambda$prepareTask$0(OptimizeImportsProcessor.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$null$0(AbstractLayoutCodeProcessor.java:234)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:905)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$preprocessFile$1(AbstractLayoutCodeProcessor.java:234)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.runWithoutProgress(AbstractLayoutCodeProcessor.java:434)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction._addImport(AddImportAction.java:238)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.lambda$null$2(AddImportAction.java:213)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:256)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.lambda$null$3(AddImportAction.java:213)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:905)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.lambda$addImport$4(AddImportAction.java:213)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.addImport(AddImportAction.java:213)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.execute(AddImportAction.java:89)
	at com.intellij.codeInsight.hint.HintManagerImpl.performCurrentQuestionAction(HintManagerImpl.java:212)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invoke(ShowIntentionActionsHandler.java:87)
	at com.intellij.codeInsight.intention.actions.ShowIntentionActionsAction.actionPerformed(ShowIntentionActionsAction.java:51)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:677)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krasa** [comment]
So did you provide the file?

**Comment by krasa** [comment]
Fixed
