### ISSUE TITLE
Eclipse Import Optimizer failed & file-encoding auto change

### ISSUE THREAD

**Issue by newpanderking** [krasa/EclipseCodeFormatter#114]
#### Two questions
- 1、when starting the Intellij, the error appear at once. the error stacks are shown below:
  ` Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
  krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
  at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:34)
  at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:15)
  at krasa.formatter.settings.provider.CachedProvider.get(CachedProvider.java:26)
  at krasa.formatter.plugin.EclipseImportOptimizer.getImportSorter(EclipseImportOptimizer.java:109)
  at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:60)
  at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:24)
  at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:48)
  at com.intellij.codeInsight.actions.OptimizeImportsProcessor.a(OptimizeImportsProcessor.java:94)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
  at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
  at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.runWithoutProgress(AbstractLayoutCodeProcessor.java:434)
  at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.b(AddImportAction.java:238)
  at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.a(AddImportAction.java:213)
  at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:256)
  at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.c(AddImportAction.java:213)
  at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
  at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.d(AddImportAction.java:213)
  at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
  at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
  at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
  at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.e(AddImportAction.java:213)
  at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.execute(AddImportAction.java:89)
  at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.a(ImportClassFixBase.java:331)
  at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:301)
  at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.doFix(ImportClassFixBase.java:331)
  at com.intellij.codeInsight.daemon.impl.JavaReferenceImporter.autoImportReferenceAt(JavaReferenceImporter.java:72)
  at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.a(ShowAutoImportPass.java:120)
  at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.addImports(ShowAutoImportPass.java:85)
  at com.intellij.codeInsight.daemon.impl.DefaultHighlightInfoProcessor.a(DefaultHighlightInfoProcessor.java:70)
  at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
  at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
  at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
  at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
  at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
  at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
  at java.awt.EventQueue.access$500(EventQueue.java:97)
  at java.awt.EventQueue$3.run(EventQueue.java:709)
  at java.awt.EventQueue$3.run(EventQueue.java:703)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
  at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
    at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:34)
    at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:15)
    at krasa.formatter.settings.provider.CachedProvider.get(CachedProvider.java:26)
    at krasa.formatter.plugin.EclipseImportOptimizer.getImportSorter(EclipseImportOptimizer.java:109)
    at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:60)
    at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:24)
    at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:48)
    at com.intellij.codeInsight.actions.OptimizeImportsProcessor.a(OptimizeImportsProcessor.java:94)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.runWithoutProgress(AbstractLayoutCodeProcessor.java:434)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.b(AddImportAction.java:238)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.a(AddImportAction.java:213)
    at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:256)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.c(AddImportAction.java:213)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.d(AddImportAction.java:213)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.e(AddImportAction.java:213)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.execute(AddImportAction.java:89)
    at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.a(ImportClassFixBase.java:331)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:301)
    at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.doFix(ImportClassFixBase.java:331)
    at com.intellij.codeInsight.daemon.impl.JavaReferenceImporter.autoImportReferenceAt(JavaReferenceImporter.java:72)
    at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.a(ShowAutoImportPass.java:120)
    at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.addImports(ShowAutoImportPass.java:85)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightInfoProcessor.a(DefaultHighlightInfoProcessor.java:70)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
    at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:34)
    at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:15)
    at krasa.formatter.settings.provider.CachedProvider.get(CachedProvider.java:26)
    at krasa.formatter.plugin.EclipseImportOptimizer.getImportSorter(EclipseImportOptimizer.java:109)
    at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:60)
    at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:24)
    at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:48)
    at com.intellij.codeInsight.actions.OptimizeImportsProcessor.a(OptimizeImportsProcessor.java:94)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.runWithoutProgress(AbstractLayoutCodeProcessor.java:434)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.b(AddImportAction.java:238)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.a(AddImportAction.java:213)
    at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:256)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.c(AddImportAction.java:213)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.d(AddImportAction.java:213)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.e(AddImportAction.java:213)
    at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.execute(AddImportAction.java:89)
    at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.a(ImportClassFixBase.java:331)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:301)
    at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.doFix(ImportClassFixBase.java:331)
    at com.intellij.codeInsight.daemon.impl.JavaReferenceImporter.autoImportReferenceAt(JavaReferenceImporter.java:72)
    at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.a(ShowAutoImportPass.java:120)
    at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.addImports(ShowAutoImportPass.java:85)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightInfoProcessor.a(DefaultHighlightInfoProcessor.java:70)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`
- 2、 Intellij  file-encoding always auto change to `utf-8` when I format my code with eclipse codeformatter, but my real file-encoding is `gbk`.  Eclipse code formatter will change file-encoding??

**Comment by krasa** [comment]
1} do you use auto save plugin? In the next version,a nice error popup will appear...

2) no. The plugin should do nothing with the encoding.

**Comment by newpanderking** [comment]
- oh, sorry, I haven`t used any auto save plugin. If I make the eclipse-code-formatter disabled, the encoding will not change when I format the code. So it looks like the the plugin changes my encoding.

**Comment by krasa** [comment]
Strange, I cant reproduce the issue with encoding.

**Comment by markiewb** [comment]
@newpanderking: Please provide your settings. I guess the encoding configuration is in one of them.
