### ISSUE TITLE
TokenManager.lastIndexIn error

### ISSUE THREAD

**Issue by bgranvea** [krasa/EclipseCodeFormatter#115]
Since I upgraded to latest version (15.9.132.637.0), I have the following error quite often:

2016-09-07 15:04:50,290 [79827744]  DEBUG - plugin.EclipseCodeStyleManager - format ServerCoreFake.java 29731 30186 
2016-09-07 15:04:50,290 [79827744]  DEBUG - er.plugin.EclipseCodeFormatter - #format 29731-30186 
2016-09-07 15:04:50,290 [79827744]  DEBUG - er.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen ServerCoreFake.java 
2016-09-07 15:04:50,295 [79827749]  DEBUG - er.EclipseJavaFormatterAdapter - #formatInternal 
2016-09-07 15:04:50,295 [79827749]  DEBUG - er.EclipseJavaFormatterAdapter - #starting to format by eclipse formatter 
2016-09-07 15:04:50,326 [79827780]  ERROR - plugin.EclipseCodeStyleManager - null 
java.lang.AssertionError
	at org.eclipse.jdt.internal.formatter.TokenManager.lastIndexIn(Unknown Source)
	at org.eclipse.jdt.internal.formatter.linewrap.WrapPreparator.prepareElementsList(Unknown Source)
	at org.eclipse.jdt.internal.formatter.linewrap.WrapPreparator.visit(Unknown Source)
	at org.eclipse.jdt.core.dom.ParameterizedType.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(Unknown Source)
	at org.eclipse.jdt.core.dom.ParameterizedType.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(Unknown Source)
	at org.eclipse.jdt.core.dom.ClassInstanceCreation.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(Unknown Source)
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(Unknown Source)
	at org.eclipse.jdt.core.dom.ReturnStatement.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(Unknown Source)
	at org.eclipse.jdt.core.dom.Block.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(Unknown Source)
	at org.eclipse.jdt.core.dom.TryStatement.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(Unknown Source)
	at org.eclipse.jdt.core.dom.Block.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(Unknown Source)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(Unknown Source)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(Unknown Source)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(Unknown Source)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareWraps(Unknown Source)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(Unknown Source)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(Unknown Source)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(Unknown Source)
	at krasa.formatter.adapter.EclipseJavaFormatterAdapter.format(EclipseJavaFormatterAdapter.java:82)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.format(JavaCodeFormatterFacade.java:55)
	at krasa.formatter.plugin.EclipseCodeFormatter.reformat(EclipseCodeFormatter.java:112)
	at krasa.formatter.plugin.EclipseCodeFormatter.formatWhenEditorIsOpen(EclipseCodeFormatter.java:90)
	at krasa.formatter.plugin.EclipseCodeFormatter.format(EclipseCodeFormatter.java:55)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:221)
	at krasa.formatter.plugin.EclipseCodeStyleManager.format(EclipseCodeStyleManager.java:112)
	at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:75)

**Comment by krasa** [comment]
Eclipse bug. Could you post the code to reproduce it?

**Comment by bgranvea** [comment]
hum it seems difficult because the source belongs to my company. I will try to find a smallest test case to reproduce.

**Comment by dosoft** [comment]
```
public class Class1 {
  private void method1(Event event) {
    Map<String, Map<String, List<Index>>> indexes = event.getIndexes();
  }
}
```

throws this exception.

**Comment by krasa** [comment]
Thanks I will report a bug. As a workaround -  it should work fine, if you disable assertions  (remove -ea from idea vmoptions)

**Comment by krasa** [comment]
https://dev.eclipse.org/recommenders/community/aeri/v2/#!/submissions/yRvbqb4nnkF5R3y3zpCJb9qHQqe12zCMO2ATdoKEaT3p91VfYAqgLWpLmjROFzyv

**Comment by krasa** [comment]
Turns out assertions can be disabled in the plugin... You can update now.
