### ISSUE TITLE
C++: Null Pointer Exception on "Reformat Code"

### ISSUE THREAD

**Issue by annaseufert** [krasa/EclipseCodeFormatter#117]
i get this error message when running Code > Reformat Code:

null
java.lang.NullPointerException
    at org.eclipse.cdt.core.CCorePlugin.log(Unknown Source)
    at org.eclipse.cdt.internal.formatter.CCodeFormatter.formatRegions(Unknown Source)
    at org.eclipse.cdt.internal.formatter.CCodeFormatter.format(Unknown Source)
    at org.eclipse.cdt.internal.formatter.CCodeFormatter.format(Unknown Source)
    at krasa.formatter.adapter.CppCodeFormatterFacade.format(CppCodeFormatterFacade.java:53)
    at krasa.formatter.plugin.EclipseCodeFormatter.reformat(EclipseCodeFormatter.java:112)
    at krasa.formatter.plugin.EclipseCodeFormatter.formatWhenEditorIsOpen(EclipseCodeFormatter.java:90)
    at krasa.formatter.plugin.EclipseCodeFormatter.format(EclipseCodeFormatter.java:55)
    at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:214)
    at krasa.formatter.plugin.EclipseCodeStyleManager.format(EclipseCodeStyleManager.java:112)
    at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:75)
    at com.intellij.codeInsight.actions.ReformatCodeProcessor.b(ReformatCodeProcessor.java:131)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:234)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:332)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.b(AbstractLayoutCodeProcessor.java:406)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:403)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:793)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krasa** [comment]
It seems that the only way to fix it would be to powermock a final method org.eclipse.core.runtime.Plugin#getLog

**Comment by krasa** [comment]
c++ support was removed.
