### ISSUE TITLE
NumberFormatException while optimising imports

### ISSUE THREAD

**Issue by rajsrivastav1919** [krasa/EclipseCodeFormatter#120]
IDEA version - 2016.3 & 2016.3.1
Plugin version - 16.0.163.3094

Stack trace -

Eclipse Import Optimizer failed: imports: import org.apache.logging.log4j.Level;import org.apache.logging.log4j.core.config.Configurator;import org.yaml.snakeyaml.Yaml;import java.io.IOException;import java.io.InputStream;import java.util.TimeZone;, settings: null
krasa.formatter.plugin.ImportSorterException: imports: import org.apache.logging.log4j.Level;import org.apache.logging.log4j.core.config.Configurator;import org.yaml.snakeyaml.Yaml;import java.io.IOException;import java.io.InputStream;import java.util.TimeZone;, settings: null
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:89)
	at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:22)
	at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:48)
	at com.intellij.codeInsight.actions.OptimizeImportsProcessor.a(OptimizeImportsProcessor.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:236)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:927)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:232)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:334)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.b(AbstractLayoutCodeProcessor.java:408)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:405)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NumberFormatException: For input string: "API"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at krasa.formatter.settings.provider.ImportOrderProvider$1.compare(ImportOrderProvider.java:44)
	at krasa.formatter.settings.provider.ImportOrderProvider$1.compare(ImportOrderProvider.java:41)
	at java.util.TreeMap.compare(TreeMap.java:1295)
	at java.util.TreeMap.put(TreeMap.java:538)
	at java.util.AbstractMap.putAll(AbstractMap.java:281)
	at java.util.TreeMap.putAll(TreeMap.java:327)
	at krasa.formatter.settings.provider.ImportOrderProvider.loadImportOrderFile(ImportOrderProvider.java:47)
	at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:32)
	at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:15)
	at krasa.formatter.settings.provider.CachedProvider.get(CachedProvider.java:26)
	at krasa.formatter.plugin.EclipseImportOptimizer.getImportSorter(EclipseImportOptimizer.java:115)
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:66)
	... 38 more

**Comment by krasa** [comment]
please attach the import config file.

**Comment by rajsrivastav1919** [comment]
Found the issue in import config file.
It was maintained by my organisation, so I thought it would be in the correct format.
Hence, closing the ticket.

Thanks anyways.
