### ISSUE TITLE
IndexOutOfBoundsException after upgrading to Intellij 2016.3

### ISSUE THREAD

**Issue by robtha** [krasa/EclipseCodeFormatter#122]
Index: 3530, Size: 3494
java.lang.IndexOutOfBoundsException: Index: 3530, Size: 3494
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.eclipse.jdt.internal.formatter.TokenManager.get(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TokenManager.findFirstTokenInLine(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TokenManager.findFirstTokenInLine(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TextEditsBuilder.bufferIndent(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TextEditsBuilder.bufferWhitespaceBefore(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TextEditsBuilder.token(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TokenTraverser.traverse(Unknown Source)
	at org.eclipse.jdt.internal.formatter.TokenManager.traverse(Unknown Source)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(Unknown Source)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(Unknown Source)
	at krasa.formatter.adapter.EclipseJavaFormatterAdapter.format(EclipseJavaFormatterAdapter.java:82)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.format(JavaCodeFormatterFacade.java:55)
	at krasa.formatter.plugin.EclipseCodeFormatter.reformat(EclipseCodeFormatter.java:112)
	at krasa.formatter.plugin.EclipseCodeFormatter.formatWhenEditorIsOpen(EclipseCodeFormatter.java:90)
	at krasa.formatter.plugin.EclipseCodeFormatter.format(EclipseCodeFormatter.java:55)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:232)
	at krasa.formatter.plugin.EclipseCodeStyleManager.format(EclipseCodeStyleManager.java:123)
	at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:86)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.a(ReformatCodeProcessor.java:129)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:236)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:927)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:334)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.b(AbstractLayoutCodeProcessor.java:408)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.a(AbstractLayoutCodeProcessor.java:405)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krasa** [comment]
duplicates #126
