### ISSUE TITLE
Cannot set value for field CONTINUATION_INDENT_SIZE

### ISSUE THREAD

**Issue by friedfilibuster** [krasa/EclipseCodeFormatter#131]
I've been getting this exception randomly.
Version info:
IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Eclipse Code Formatter Version: 16.3.132.637.0
[code_format_v10.txt](https://github.com/krasa/EclipseCodeFormatter/files/906293/code_format_v10.txt)
[vegas.importorder.txt](https://github.com/krasa/EclipseCodeFormatter/files/906295/vegas.importorder.txt)
![image](https://cloud.githubusercontent.com/assets/1928331/24811391/bf89f2ae-1b7a-11e7-9629-ee309ac0bb3c.png)

```
Cannot init ProjectCodeStyleSettingsManager component state: java.lang.RuntimeException: Cannot set value for field CONTINUATION_INDENT_SIZE
com.intellij.util.xmlb.XmlSerializationException: java.lang.RuntimeException: Cannot set value for field CONTINUATION_INDENT_SIZE
	at com.intellij.util.xmlb.XmlSerializer.deserializeInto(XmlSerializer.java:102)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettings$IndentOptions.deserialize(CommonCodeStyleSettings.java:956)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettings.readExternal(CommonCodeStyleSettings.java:161)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.readExternal(CommonCodeStyleSettingsManager.java:173)
	at com.intellij.psi.codeStyle.CodeStyleSettings.readExternal(CodeStyleSettings.java:628)
	at com.intellij.openapi.util.DefaultJDOMExternalizer.readExternal(DefaultJDOMExternalizer.java:282)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.loadState(CodeStyleSettingsManager.java:97)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.loadState(CodeStyleSettingsManager.java:33)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:345)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:292)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:92)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:233)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:44)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getSettings(CodeStyleSettingsManager.java:70)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.getSettings(CodeStyleManagerImpl.java:618)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.<init>(CodeStyleManagerImpl.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:228)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at com.intellij.psi.codeStyle.CodeStyleManager.getInstance(CodeStyleManager.java:50)
	at krasa.formatter.plugin.ProjectCodeStyleInstaller.uninstallCodeFormatter(ProjectCodeStyleInstaller.java:85)
	at krasa.formatter.plugin.ProjectCodeStyleInstaller.changeFormatterTo(ProjectCodeStyleInstaller.java:49)
	at krasa.formatter.settings.ProjectSettingsComponent.install(ProjectSettingsComponent.java:52)
	at krasa.formatter.settings.ProjectSettingsComponent.projectOpened(ProjectSettingsComponent.java:80)
	at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:392)
	at com.intellij.openapi.project.impl.ProjectImpl.access$100(ProjectImpl.java:69)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:427)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:97)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.k(ProjectManagerImpl.java:686)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:357)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:923)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:199)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:186)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:422)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:89)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:337)
	at com.intellij.openapi.progress.impl.CoreProgressManager.b(CoreProgressManager.java:339)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:323)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:190)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:437)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:189)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:619)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:661)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy50.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:350)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:348)
	at com.intellij.idea.IdeaApplication.a(IdeaApplication.java:202)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: Cannot set value for field CONTINUATION_INDENT_SIZE
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:112)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:66)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:232)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:186)
	at com.intellij.util.xmlb.XmlSerializer.deserializeInto(XmlSerializer.java:96)
	... 116 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.intellij.util.xmlb.XmlSerializerImpl.doSet(XmlSerializerImpl.java:255)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:109)
	... 120 more
```

**Comment by krasa** [comment]
IntelliJ bug imho.

**Comment by krasa** [comment]
Look into .IntelliJIdea2017.1\config\codestyles and check that CONTINUATION_INDENT_SIZE value is a number

**Comment by nonexpectation** [comment]
Here's what I see
[vegas.xml.txt](https://github.com/krasa/EclipseCodeFormatter/files/906842/vegas.xml.txt)


```
...
<option name="CONTINUATION_INDENT_SIZE" value="2" />
...
```


It it's an IntelliJ bug I'll file it with them. Thanks for checking.

**Comment by krasa** [comment]
It could be also in the project folder in *.ipr or .idea/codeStyleSettings.xml

**Comment by nonexpectation** [comment]
I see the same thing in .idea/codeStyleSettings.xml
[codeStyleSettings.xml.txt](https://github.com/krasa/EclipseCodeFormatter/files/910955/codeStyleSettings.xml.txt)
 I grepped through every other file and didn't see anything different.

**Comment by krasa** [comment]
Solved?
