### ISSUE TITLE
Executing format locks up IDEA input for 10 seconds, debug log

### ISSUE THREAD

**Issue by AtomicStryker** [krasa/EclipseCodeFormatter#165]
When triggering the eclipse format, the format itself proceeds as expected, but then i find that i cannot type anything in Intellij for 10 seconds. After the 10 seconds i can resume typing. No visible errors. When enabling debug logging (you need to update the instruction to the new Menu name "Debug Log Settings"):

2018-04-29 13:01:37,890 [7229449]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: krasa.formatter 
2018-04-29 13:01:39,298 [7230857]  DEBUG - ProxyCodeStyleManagerDelegator - invoking overriding {}({})reformatText[PsiJavaFile:Test.java, [(0,4625)]] 
2018-04-29 13:01:39,298 [7230857]  DEBUG - CodeStyleManager_IJ_2016_3plus - format Test.java 0 4625 
2018-04-29 13:01:39,299 [7230858]  DEBUG - er.plugin.EclipseCodeFormatter - #format 0-4625 
2018-04-29 13:01:39,299 [7230858]  DEBUG - er.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen Test.java 
2018-04-29 13:01:39,301 [7230860]  DEBUG - er.EclipseJavaFormatterAdapter - #formatInternal 
2018-04-29 13:01:39,302 [7230861]  DEBUG - er.EclipseJavaFormatterAdapter - #starting to format by eclipse formatter 
2018-04-29 13:01:39,335 [7230894]  DEBUG - er.EclipseJavaFormatterAdapter - reformatting done 
2018-04-29 13:01:39,339 [7230898]  DEBUG - er.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen done 
2018-04-29 13:01:49,342 [7240901]  ERROR - ij.ide.IdeEventQueue.typeahead - Typeahead timeout is exceeded: 10049 
java.lang.RuntimeException: Typeahead timeout is exceeded: 10049
	at com.intellij.ide.IdeEventQueue.lambda$isTypeaheadTimeoutExceeded$19(IdeEventQueue.java:1149)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-04-29 13:01:49,343 [7240902]  ERROR - ij.ide.IdeEventQueue.typeahead - IntelliJ IDEA 2018.1.2  Build #IU-181.4668.68 
2018-04-29 13:01:49,343 [7240902]  ERROR - ij.ide.IdeEventQueue.typeahead - JDK: 1.8.0_152-release 
2018-04-29 13:01:49,343 [7240902]  ERROR - ij.ide.IdeEventQueue.typeahead - VM: OpenJDK 64-Bit Server VM 
2018-04-29 13:01:49,343 [7240902]  ERROR - ij.ide.IdeEventQueue.typeahead - Vendor: JetBrains s.r.o 
2018-04-29 13:01:49,343 [7240902]  ERROR - ij.ide.IdeEventQueue.typeahead - OS: Windows 10 
2018-04-29 13:01:49,343 [7240902]  ERROR - ij.ide.IdeEventQueue.typeahead - Last Action: ReformatCode 

I am appending my eclipse formatter export. (Rename file ending to xml as github does not take that)
[formatter.txt](https://github.com/krasa/EclipseCodeFormatter/files/1958667/formatter.txt)

**Comment by AtomicStryker** [comment]
Aaaaand the problem does not reoccur after restarting IDEA. I'll just go back to my corner.
