### ISSUE TITLE
java.lang.ClassCastException: com.intellij.psi.impl.source.PsiExpressionCodeFragmentImpl cannot be cast to com.intellij.psi.PsiJavaFile

### ISSUE THREAD

**Issue by bojanantonovic** [krasa/EclipseCodeFormatter#186]
I get this one (latest version of IntelliJ):
```
java.lang.ClassCastException: com.intellij.psi.impl.source.PsiExpressionCodeFragmentImpl cannot be cast to com.intellij.psi.PsiJavaFile
	at krasa.formatter.plugin.EclipseImportOptimizer.processFile(EclipseImportOptimizer.java:30)
	at com.intellij.codeInsight.actions.OptimizeImportsProcessor.prepareTask(OptimizeImportsProcessor.java:91)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.preprocessFile(AbstractLayoutCodeProcessor.java:229)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.runWithoutProgress(AbstractLayoutCodeProcessor.java:456)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction._addImport(AddImportAction.java:219)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.lambda$null$2(AddImportAction.java:208)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:124)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:263)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:319)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:321)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:244)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:126)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:361)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.lambda$addImport$3(AddImportAction.java:207)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:320)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.addImport(AddImportAction.java:201)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.execute(AddImportAction.java:77)
	at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.lambda$doFix$7(ImportClassFixBase.java:333)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:377)
	at com.intellij.codeInsight.daemon.impl.quickfix.ImportClassFixBase.doFix(ImportClassFixBase.java:333)
	at com.intellij.codeInsight.daemon.impl.JavaReferenceImporter.autoImportReferenceAt(JavaReferenceImporter.java:76)
	at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.importUnambiguousImports(ShowAutoImportPass.java:101)
	at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.addImports(ShowAutoImportPass.java:72)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by krasa** [comment]
This should do: https://github.com/krasa/EclipseCodeFormatter/releases/download/18.4.181.000.0-Eclipse_2019-03/EclipseFormatter.zip
