### ISSUE TITLE
Eclipse Luna support in Idea 2020.1

### ISSUE THREAD

**Issue by ZsergUA** [krasa/EclipseCodeFormatter#205]
I moved to Idea 2020.1 and unfortunately Eclipse Code Formatter version: 16.6.132.637.0.Eclipse_4.6.3 stopped working. Logs at the bottom

I can't move to new version of plugin right now, cause project stuck on formatter profile from Eclipse Luna (4.4) version and all subsequent versions of Eclipse are formatting differently.

I found that newer versions of Eclipse make it possible to format with former Luna formatter using this plugin [alostale/luna-java-formatter](/alostale/luna-java-formatter). But looks like Eclipse Code Formatte just ignores if it is in the eclipse folder

Is there any chance you can support Luna formatter either by fixing 16.6.132.637.0.Eclipse_4.6.3 version to work with Idea 2020.1 or by supporting eclipse 3pp plugins for formatting

```
2020-05-01 04:19:34,807 [ 697993]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: krasa.formatter 
2020-05-01 04:19:41,933 [ 705119]  ERROR - Container.ComponentManagerImpl - com.intellij.psi.codeStyle.CodeStyleManager requested as a service, but it is a component - convert it to a service or change call to project.getComponent() 
com.intellij.diagnostic.PluginException: com.intellij.psi.codeStyle.CodeStyleManager requested as a service, but it is a component - convert it to a service or change call to project.getComponent()
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:446)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:58)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:75)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:417)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:379)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:24)
	at com.intellij.psi.codeStyle.CodeStyleManager.getInstance(CodeStyleManager.java:40)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$null$0(ReformatCodeProcessor.java:113)
	at com.intellij.openapi.editor.ex.util.EditorScrollingPositionKeeper.perform(EditorScrollingPositionKeeper.java:110)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$1(ReformatCodeProcessor.java:103)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:353)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:107)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:248)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:247)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:305)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:307)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:246)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:227)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:109)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:353)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.lambda$performFileProcessing$5(AbstractLayoutCodeProcessor.java:412)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:480)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-05-01 04:19:41,933 [ 705119]  ERROR - Container.ComponentManagerImpl - IntelliJ IDEA 2020.1  Build #IC-201.6668.121 
2020-05-01 04:19:41,933 [ 705119]  ERROR - Container.ComponentManagerImpl - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-05-01 04:19:41,933 [ 705119]  ERROR - Container.ComponentManagerImpl - OS: Windows 10 
2020-05-01 04:19:41,933 [ 705119]  ERROR - Container.ComponentManagerImpl - Last Action: ReformatCode 
2020-05-01 04:19:41,933 [ 705119]  ERROR - Container.ComponentManagerImpl - Current Command: Reformat Code 
2020-05-01 04:19:41,933 [ 705119]  DEBUG - ProxyCodeStyleManagerDelegator - invoking overriding {}({})reformatText[PsiJavaFile:AbstractGrantServiceTest.java, [(0,60652)]] 
2020-05-01 04:19:41,933 [ 705119]  DEBUG - CodeStyleManager_IJ_2016_3plus - format AbstractGrantServiceTest.java 0 60652 
2020-05-01 04:19:41,933 [ 705119]  DEBUG - er.plugin.EclipseCodeFormatter - #format 0-60652 
2020-05-01 04:19:41,933 [ 705119]  DEBUG - er.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen AbstractGrantServiceTest.java 
2020-05-01 04:19:41,933 [ 705119]  ERROR - CodeStyleManager_IJ_2016_3plus - com/intellij/psi/impl/JavaPsiImplementationHelper 
java.lang.NoClassDefFoundError: com/intellij/psi/impl/JavaPsiImplementationHelper
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.getLanguageLevel(JavaCodeFormatterFacade.java:133)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.format(JavaCodeFormatterFacade.java:54)
	at krasa.formatter.plugin.EclipseCodeFormatter.reformat(EclipseCodeFormatter.java:112)
	at krasa.formatter.plugin.EclipseCodeFormatter.formatWhenEditorIsOpen(EclipseCodeFormatter.java:90)
	at krasa.formatter.plugin.EclipseCodeFormatter.format(EclipseCodeFormatter.java:55)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:232)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatInternal(EclipseCodeStyleManager.java:135)
	at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.invoke(ProxyCodeStyleManagerDelegator.java:41)
	at net.sf.cglib.empty.Object$$EnhancerByCGLIB$$a6c18dd5.reformatText(<generated>)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$null$0(ReformatCodeProcessor.java:113)
	at com.intellij.openapi.editor.ex.util.EditorScrollingPositionKeeper.perform(EditorScrollingPositionKeeper.java:110)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$1(ReformatCodeProcessor.java:103)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:353)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:107)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:248)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:247)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:305)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:307)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:246)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:227)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:109)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:353)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.lambda$performFileProcessing$5(AbstractLayoutCodeProcessor.java:412)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:480)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-05-01 04:19:41,933 [ 705119]  ERROR - CodeStyleManager_IJ_2016_3plus - IntelliJ IDEA 2020.1  Build #IC-201.6668.121 
2020-05-01 04:19:41,933 [ 705119]  ERROR - CodeStyleManager_IJ_2016_3plus - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-05-01 04:19:41,933 [ 705119]  ERROR - CodeStyleManager_IJ_2016_3plus - OS: Windows 10 
2020-05-01 04:19:41,933 [ 705119]  ERROR - CodeStyleManager_IJ_2016_3plus - Plugin to blame: Eclipse Code Formatter version: 16.6.132.637.0.Eclipse_4.6.3 
2020-05-01 04:19:41,933 [ 705119]  ERROR - CodeStyleManager_IJ_2016_3plus - Last Action: ReformatCode 
2020-05-01 04:19:41,933 [ 705119]  ERROR - CodeStyleManager_IJ_2016_3plus - Current Command: Reformat Code 
2020-05-01 04:19:49,527 [ 712713]   INFO - j.ide.actions.RevealFileAction - Exit code 1 
```

**Comment by krasa** [comment]
Install any new version and point it to your eclipse installation, dunno why it says '4.5+', it seems to work even for 4.4.
![image](https://user-images.githubusercontent.com/1160875/80816946-c0a94a80-8bd0-11ea-9c70-eaa747333b5a.png)

**Comment by ZsergUA** [comment]
**Works like a charm, thanks.**
That message regarding Mars+ Eclipse version is really confusing in this case. It just stopped me trying.

Probably it has to be mention 4.4/ Luna at least
