### ISSUE TITLE
Reformatting code freezes Intellij

### ISSUE THREAD

**Issue by Reddone** [krasa/EclipseCodeFormatter#210]
> What steps will reproduce the issue?

IntelliJ freezes when I issue the reformat code command. Prior to updating the plugin everything was fine.

> What is the expected result?

The code will be reformatted by the plugin.

> What happens instead?

Intellij freezes with the "Reformat code" task blocked.

> Paste information about IDE and OS (it can be copied from Help | About dialog).

IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.3.0-61-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 962M
Cores: 4
Non-Bundled Plugins: Lombook Plugin, org.jetbrains.plugins.hocon, org.jetbrains.kotlin, mobi.hsz.idea.gitignore, org.intellij.scala
Current Desktop: ubuntu:GNOME

**Comment by krasa** [comment]
please post a threadump

**Comment by Reddone** [comment]
I did a grep on the threadump looking for the "eclipse" keyword and found this:

"AWT-EventQueue-0" #28 prio=6 os_prio=0 cpu=137839,55ms elapsed=234,03s tid=0x00007f3d680fd800 nid=0x2796 runnable  [0x00007f3d3fadd000]
   java.lang.Thread.State: RUNNABLE
        at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:137)
        at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:80)
        at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:24)
        at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:106)
        at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:98)
        at com.intellij.openapi.module.ModuleUtilCore.findModuleForFile(ModuleUtilCore.java:72)
        at krasa.formatter.eclipse.ConfigFileLocator$DefaultModuleResolverStrategy.getModuleDirForFile(ConfigFileLocator.java:250)
        at krasa.formatter.eclipse.ConfigFileLocator.getModuleDirForFile(ConfigFileLocator.java:226)
        at krasa.formatter.eclipse.ConfigFileLocator.getNextParentModuleDirectory(ConfigFileLocator.java:235)
        at krasa.formatter.eclipse.ConfigFileLocator.traverseToFindConfigurationFileByConvention(ConfigFileLocator.java:209)
        at krasa.formatter.eclipse.JavaCodeFormatterFacade.getCodeFormatter(JavaCodeFormatterFacade.java:61)
        at krasa.formatter.eclipse.JavaCodeFormatterFacade.format(JavaCodeFormatterFacade.java:53)
        at krasa.formatter.plugin.EclipseCodeFormatter.reformat(EclipseCodeFormatter.java:110)
        at krasa.formatter.plugin.EclipseCodeFormatter.formatWhenEditorIsOpen(EclipseCodeFormatter.java:87)
        at krasa.formatter.plugin.EclipseCodeFormatter.format(EclipseCodeFormatter.java:52)
        at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:204)
        at krasa.formatter.plugin.EclipseCodeStyleManager.formatInternal(EclipseCodeStyleManager.java:128)
        at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:78)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.7/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.7/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.7/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.7/Method.java:566)
        at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.invoke(ProxyCodeStyleManagerDelegator.java:42)
        at net.sf.cglib.empty.Object$$EnhancerByCGLIB$$a6c18dd5.reformatText(<generated>)
        at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$null$0(ReformatCodeProcessor.java:113)
        at com.intellij.codeInsight.actions.ReformatCodeProcessor$$Lambda$4715/0x00000001028df040.run(Unknown Source)
        at com.intellij.openapi.editor.ex.util.EditorScrollingPositionKeeper.perform(EditorScrollingPositionKeeper.java:110)
        at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$1(ReformatCodeProcessor.java:103)
        at com.intellij.codeInsight.actions.ReformatCodeProcessor$$Lambda$4714/0x00000001028dfc40.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(java.base@11.0.7/FutureTask.java:264)
at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:353)
        at com.intellij.openapi.command.WriteCommandAction$$Lambda$4678/0x00000001028c5c40.run(Unknown Source)
        at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:107)
        at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
        at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:248)
        at com.intellij.openapi.command.WriteCommandAction$$Lambda$4681/0x00000001028c4840.run(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
        at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:247)
        at com.intellij.openapi.command.WriteCommandAction$$Lambda$4679/0x00000001028c5040.run(Unknown Source)
        at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:305)
        at com.intellij.openapi.command.WriteCommandAction$$Lambda$4680/0x00000001028c5440.run(Unknown Source)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
        at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:307)
        at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:246)
        at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:227)
        at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:109)
        at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:353)
        at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.lambda$performFileProcessing$5(AbstractLayoutCodeProcessor.java:413)
        at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask$$Lambda$4677/0x00000001028c5840.run(Unknown Source)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:480)
        at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$461/0x000000010061a840.run(Unknown Source)
        at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:124)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
        at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.7/InvocationEvent.java:313)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.7/EventQueue.java:776)
        at java.awt.EventQueue$4.run(java.desktop@11.0.7/EventQueue.java:727)
        at java.awt.EventQueue$4.run(java.desktop@11.0.7/EventQueue.java:721)
        at java.security.AccessController.doPrivileged(java.base@11.0.7/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.7/ProtectionDomain.java:85)
        at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.7/EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
        at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
        at com.intellij.ide.IdeEventQueue$$Lambda$446/0x00000001005f4440.compute(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
        at com.intellij.ide.IdeEventQueue$$Lambda$445/0x00000001005f5440.run(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.7/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.7/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.7/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.7/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.7/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@11.0.7/EventDispatchThread.java:90)

**Comment by Reddone** [comment]
It appears to be a problem with the config file (I uninstalled and re installed the plugin) but I was having the same problem even with the correct configuration. Everything was fine until last update.

**Comment by krasa** [comment]
Could you check your settings? It seems that the resolving feature does not work properly, you could change it to something else.

![image](https://user-images.githubusercontent.com/1160875/86245602-fd31fc00-bba9-11ea-98e2-69466d367a04.png)

**Comment by Reddone** [comment]
Thanks, it worked! I always used the last checkbox ("Eclipse workspace/project/config file") but when I opened the plugin config the checkbox you mentioned was the active one and caused the reformat command to crash. Maybe the last update turned the first checkbox on?

Thanks again for the answer and the super quick response time!

**Comment by krasa** [comment]
Yes, I screwed it up. :(
New update is released, the last option should be always selected by default.

**Comment by krasa** [comment]
@Reddone could you please upload the whole threaddump folder generated for this freeze?

**Comment by Reddone** [comment]
[error.txt](https://github.com/krasa/EclipseCodeFormatter/files/4858848/error.txt)

**Comment by krasa** [comment]
Thank you! I think I found it. It could happen when a module file (iml) is located in some subfolder
![image](https://user-images.githubusercontent.com/1160875/86413867-a3712500-bcc2-11ea-9ed7-fd7e3f1a5dda.png)

**Comment by Reddone** [comment]
The project I was working on is a multimodule one, and I have multiples .iml files in subfolders. I forgot to write it in the issue because I thought that it had nothing to do with the error

**Comment by krasa** [comment]
That's fine, you couldn't know that such detail is relevant. :-)
