### ISSUE TITLE
failed to format with Eclipse Code Formatter. Invalid byte 1 of 1-byte UTF-8 sequence.

### ISSUE THREAD

**Issue by wangxuekai** [krasa/EclipseCodeFormatter#215]
IDEA 2020.2 
`failed to format with Eclipse Code Formatter. Invalid byte 1 of 1-byte UTF-8 sequence.`

**Comment by krasa** [comment]
anything in the log?

**Comment by wangxuekai** [comment]
xml document contains chinese, it takes effect after  removal.
`org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 13; Invalid byte 1 of 1-byte UTF-8 sequence.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at krasa.formatter.utils.FileUtils.readXmlJavaSettingsFile(FileUtils.java:104)
	at krasa.formatter.utils.FileUtils.readXmlJavaSettingsFile(FileUtils.java:92)
	at krasa.formatter.settings.provider.CachedPropertiesProvider.readXmlFile(CachedPropertiesProvider.java:35)
	at krasa.formatter.settings.provider.JavaPropertiesProvider.readFile(JavaPropertiesProvider.java:32)
	at krasa.formatter.settings.provider.JavaPropertiesProvider.readFile(JavaPropertiesProvider.java:16)
	at krasa.formatter.settings.provider.CachedProvider.get(CachedProvider.java:27)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.getEclipseProfileOptions(JavaCodeFormatterFacade.java:149)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.getEclipseProfileOptions(JavaCodeFormatterFacade.java:117)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.newCodeFormatter(JavaCodeFormatterFacade.java:96)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.getCodeFormatter(JavaCodeFormatterFacade.java:75)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.format(JavaCodeFormatterFacade.java:53)
	at krasa.formatter.plugin.EclipseCodeFormatter.reformat(EclipseCodeFormatter.java:111)
	at krasa.formatter.plugin.EclipseCodeFormatter.formatWhenEditorIsOpen(EclipseCodeFormatter.java:87)
	at krasa.formatter.plugin.EclipseCodeFormatter.format(EclipseCodeFormatter.java:52)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:204)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatInternal(EclipseCodeStyleManager.java:128)
	at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.invoke(ProxyCodeStyleManagerDelegator.java:42)
	at net.sf.cglib.empty.Object$$EnhancerByCGLIB$$a6c18dd5.reformatText(<generated>)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$0(ReformatCodeProcessor.java:113)
	at com.intellij.openapi.editor.ex.util.EditorScrollingPositionKeeper.perform(EditorScrollingPositionKeeper.java:100)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$1(ReformatCodeProcessor.java:103)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:351)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:105)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$1(WriteCommandAction.java:246)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:980)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:245)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:303)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:187)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:305)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:244)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:225)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:107)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:351)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.lambda$performFileProcessing$5(AbstractLayoutCodeProcessor.java:417)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:475)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.`


```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="12">
    <profile kind="CodeFormatterProfile" name="P3C-CodeStyle" version="13">
        <!--可变参数的... Idea没有对应的配置项，强制insert-->
        <setting id="org.eclipse.jdt.core.formatter.insert_space_after_ellipsis" value="insert"/>
```

**Comment by sensenlinlin** [comment]
failed to format with Eclipse Code Formatter. Invalid byte 1 of 1-byte UTF-8 sequence.

**Comment by krasa** [comment]
can you upload that config file?

**Comment by krasa** [comment]
Try this
[EclipseFormatter.zip](https://github.com/krasa/EclipseCodeFormatter/files/5068851/EclipseFormatter.zip)

**Comment by wangxuekai** [comment]
> Try this
> [EclipseFormatter.zip](https://github.com/krasa/EclipseCodeFormatter/files/5068851/EclipseFormatter.zip)

Thanks!!
