### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by krasa** [krasa/EclipseCodeFormatter#218]
https://github.com/krasa/EclipseCodeFormatter-from-GoogleCode/issues/70

```
IntelliJ version:
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64

java.lang.NullPointerException
at krasa.formatter.plugin.EclipseCodeStyleManager.shouldReformatByEclipse(EclipseCodeStyleManager.java:232)
at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.invoke(ProxyCodeStyleManagerDelegator.java:42)
at net.sf.cglib.empty.Object$$EnhancerByCGLIB$$a6c18dd5.reformatText()
at org.editorconfig.configmanagement.editor.EditorConfigPreviewFile.lambda$reformat$0(EditorConfigPreviewFile.java:69)
at com.intellij.application.options.CodeStyle.doWithTemporarySettings(CodeStyle.java:281)
at org.editorconfig.configmanagement.editor.EditorConfigPreviewFile.lambda$reformat$1(EditorConfigPreviewFile.java:68)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:980)
at org.editorconfig.configmanagement.editor.EditorConfigPreviewFile.lambda$reformat$2(EditorConfigPreviewFile.java:62)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
at org.editorconfig.configmanagement.editor.EditorConfigPreviewFile.reformat(EditorConfigPreviewFile.java:60)
at org.editorconfig.configmanagement.editor.EditorConfigPreviewFile.codeStyleSettingsChanged(EditorConfigPreviewFile.java:55)
at com.intellij.psi.codeStyle.CodeStyleSettingsManager.fireCodeStyleSettingsChanged(CodeStyleSettingsManager.java:330)
at com.intellij.psi.codeStyle.CodeStyleSettingsManager.notifyCodeStyleSettingsChanged(CodeStyleSettingsManager.java:344)
at com.intellij.codeInsight.actions.FileInEditorProcessor.processCode(FileInEditorProcessor.java:123)
at com.intellij.codeInsight.actions.ReformatCodeAction.actionPerformed(ReformatCodeAction.java:140)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:610)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:620)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:471)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:220)
at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:890)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:835)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by krasa** [comment]
Fixed. Please try it https://github.com/krasa/EclipseCodeFormatter/releases/download/20.6.201.6668.0-Eclipse_2020-06-JavaOnly/EclipseFormatter.zip
