### ISSUE TITLE
Control-flow exceptions should never be logged

### ISSUE THREAD

**Issue by mvilliger** [krasa/EclipseCodeFormatter#222]
We are getting the following error in IJ 2020.1.2 using EclipseCodeFormatter version 19.5.201.6668.0-Eclipse_2019-09-JavaOnly:

```
Eclipse Import Optimizer failed

java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:198)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:88)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:168)
	at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:65)
	...
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.EmptyProgressIndicator.checkCanceled(EmptyProgressIndicator.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:124)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:225)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:49)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:687)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:30)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.getImportList(PsiJavaFileBaseImpl.java:154)
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:88)
	at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:24)
	at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:54)
	... 19 more
```

See com.intellij.openapi.diagnostic.ControlFlowException for details.
So maybe add an `instanceof` check to the `catch (Exception e)` block rethrowing the exception instead of logging it?

**Comment by krasa** [comment]
Fixed, thanks!

**Comment by mvilliger** [comment]
Thank you very much for the fast fix!
Please note that several throwables are ControlFlowExceptions. Not only ProcessCanceledException.

**Comment by krasa** [comment]
Yes, but it should be fine. :-)

**Comment by mvilliger** [comment]
Ok, fine with me. Thanks a lot! :)
