### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by petr-nehez** [krasa/EclipseCodeFormatter#227]
No idea when it could happen, just noticed the error icon.
But might be related to ignored files?

```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Subscription is active until November 28, 2021.
Runtime version: 11.0.11+9-b1460.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.18.0-305.7.1.el8_4.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 7500M
Cores: 12
Registry: documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support (1.0.12), Key Promoter X (2021.2), ch.raffael.idea.plugins.runpopup (1.3.0), com.intellij.ideolog (203.0.27.0), com.intellij.javafx (1.0.3), com.intellij.nativeDebug (212.4746.92), com.intellij.plugins.watcher (212.4746.52), com.wix.sasslint (1.1.2), com.jetbrains.ChooseRuntime (1.2), com.jetbrains.CyanTheme (1.2), com.khmelyuk.multirun (1.12), com.layoutmanager (1.4.0), com.tabnine.TabNine (0.4.4), de.ehmkah.projects.imgdiff (1.10.0), hunspell (212.4746.57), lermitage.intellij.extra.icons (1.58.0.203), lermitage.intellij.iconviewer (1.10.0.193), net.seesharpsoft.intellij.plugins.csv (2.17.1), net.seesharpsoft.intellij.plugins.file-preview (1.6.4), com.majera.intellij.codereview.bitbucket (2021.2.1.1), com.virtuslab.git-machete (1.0.0), mobi.hsz.idea.gitignore (4.2.0), name.kropp.intellij.makefile (212.4746.52), CheckStyle-IDEA (5.54.0), EclipseCodeFormatter (20.8.203.000.0-Eclipse_2020-06-JavaOnly), zielu.gittoolbox (212.6.6), GrepConsole (11.10.211.6086.0), JFormDesigner-Marketplace-Edition (7.0.4), String Manipulation (8.15.203.000.3), VisualVMLauncher (1.20.203.4204.0), com.github.setial (4.0.2), org.sonarlint.idea (5.1.0.34721), com.github.beansoft.devkit.helper (2.2), com.intellij.plugins.html.instantEditing (212.4746.57), izhangzhihao.rainbow.brackets (6.19), pro.bashsupport (2.0.3.212), ski.chrzanow.foldableprojectview (1.0.2)
Kotlin: 212-1.5.10-release-IJ4746.92
Current Desktop: GNOME
```

```
java.lang.NullPointerException
	at krasa.formatter.plugin.EclipseCodeStyleManager.isDisabledFileType(EclipseCodeStyleManager.java:246)
	at krasa.formatter.plugin.EclipseCodeStyleManager.shouldSkipFormatting(EclipseCodeStyleManager.java:226)
	at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.invoke(ProxyCodeStyleManagerDelegator.java:42)
	at net.sf.cglib.empty.Object$$EnhancerByCGLIB$$a6c18dd5.reformatText(<generated>)
	at com.intellij.httpClient.http.request.run.HttpRequestResponsePresentationHelper$getFormattedFileAsync$1$1.run(httpRequestResponsePresentationHelper.kt:35)
	at com.intellij.microservices.endpoints.EndpointsChangeTracker$Companion.withExpectedChanges(EndpointsChangeTracker.kt:19)
	at com.intellij.httpClient.http.request.run.HttpRequestUpdateManager.runUpdateAwareAction(HttpRequestUpdateManager.java:17)
	at com.intellij.httpClient.http.request.run.HttpRequestResponsePresentationHelper$getFormattedFileAsync$1.call(httpRequestResponsePresentationHelper.kt:34)
	at com.intellij.httpClient.http.request.run.HttpRequestResponsePresentationHelper$getFormattedFileAsync$1.call(httpRequestResponsePresentationHelper.kt)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lemon4github** [comment]
This NullpointerException causes problems when running a http(s) request with a json response. The json response will not be shown in view mode json. It looks like the json format will call the eclipse code formatter which crashes with this NullPointerException.

**Comment by petr-nehez** [comment]
> This NullpointerException causes problems when running a http(s) request with a json response. 

Confirmed!
When I disabled ECF plugin http(s) JSON response is well formatted:
![image](https://user-images.githubusercontent.com/1265990/127614324-90320df8-6814-4180-8a3c-e4b3033f10b1.png)

**Comment by krasa** [comment]
thanks, you can update.
