### ISSUE TITLE
Eclipse Formatter not called in IntelliJ 2024.1 EAP

### ISSUE THREAD

**Issue by jhonnen** [krasa/EclipseCodeFormatter#266]
> What steps will reproduce the issue?

Format a Java file with enabled Eclipse Formatter plugin.

> What is the expected result?

File is formatted according to Eclipse Formatter config

> What happens instead?

File is apparently formatted by the built in IntelliJ formatter

> Paste information about IDE and OS (it can be copied from Help | About dialog).

Not working in
```
IntelliJ IDEA 2024.1 EAP (Ultimate Edition)
Build #IU-241.9959.31, built on January 26, 2024
...
Runtime version: 21.0.2+13-b341.4 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 24576M
Cores: 32
Registry:
  debugger.new.tool.window.layout=true
  ide.hide.real.module.name=true
  ide.experimental.ui=true
  ide.images.show.chessboard=true
  markdown.open.vcs.log.link=true
Non-Bundled Plugins:
  EclipseCodeFormatter (23.3.223.000.0-Eclipse_2023-03)
Kotlin: 241.9959.31-IJ
```

working in
```
IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Build #IU-233.14015.106, built on January 25, 2024
...
Runtime version: 17.0.9+7-b1087.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  directory.access.checker.enabled=false
Non-Bundled Plugins:
  EclipseCodeFormatter (23.3.223.000.0-Eclipse_2023-03)
Kotlin: 233.14015.106-IJ
```

2023.3.3 contains the following log entries when formatting:
```
2024-01-31 10:20:33,747 [  32540]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level ALL is set for the following category: krasa.formatter
2024-01-31 10:20:33,747 [  32540]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level ALL is set for the following category: #krasa.formatter
2024-01-31 10:20:33,747 [  32540]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level ALL is set for the following category: krasa.formatter
2024-01-31 10:20:38,075 [  36868]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
2024-01-31 10:20:38,158 [  36951]   INFO - #c.i.p.c.ProjectCodeStyleSettingsManager - Saving Project code style
2024-01-31 10:20:38,165 [  36958]   INFO - #c.i.p.c.ProjectCodeStyleSettingsManager - Project code style saved
2024-01-31 10:20:38,188 [  36981]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=infrastructure-intellij-plugins, containerState=COMPONENT_CREATED, componentStore=...)RunManager took 20 ms
2024-01-31 10:20:50,879 [  49672]   FINE - krasa.formatter.plugin.ProxyCodeStyleManagerDelegator - invoking overriding {}({})reformatText[PsiJavaFile:MethodName.java, [(0,2063)]]
2024-01-31 10:20:50,879 [  49672]   FINE - krasa.formatter.plugin.EclipseCodeStyleManager_IJ_2016_3plus - format MethodName.java 0 2063
2024-01-31 10:20:50,879 [  49672]   FINE - krasa.formatter.plugin.EclipseCodeFormatter - #format 0-2063
2024-01-31 10:20:50,879 [  49672]   FINE - krasa.formatter.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen MethodName.java
2024-01-31 10:20:50,880 [  49673]   FINE - krasa.formatter.adapter.EclipseJavaFormatterAdapter - #formatInternal
2024-01-31 10:20:50,880 [  49673]   FINE - krasa.formatter.adapter.EclipseJavaFormatterAdapter - #starting to format by eclipse formatter
2024-01-31 10:20:50,886 [  49679]   FINE - krasa.formatter.adapter.EclipseJavaFormatterAdapter - reformatting done
2024-01-31 10:20:50,894 [  49687]   FINE - krasa.formatter.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen done
```

2024.1 has no log entries at all

**Comment by jhonnen** [comment]
The issue is reproducible when debugging 201ffb6d:
```
java.lang.NoSuchMethodException: krasa.formatter.plugin.EclipseCodeStyleManager_IJ_2016_3plus.reformatText(com.intellij.psi.PsiFile,java.util.Collection,boolean)
	at java.base/java.lang.Class.getMethod(Class.java:2395)
	at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.getOverridingMethod(ProxyCodeStyleManagerDelegator.java:67)
	at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.invoke(ProxyCodeStyleManagerDelegator.java:31)
	at net.sf.cglib.empty.Object$$EnhancerByCGLIB$$a6c18dd5.reformatText(<generated>)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.doReformat(ReformatCodeProcessor.java:221)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$5(ReformatCodeProcessor.java:166)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.runWithLocalSettings(CodeStyleSettingsManager.java:113)
	at com.intellij.application.options.CodeStyle.runWithLocalSettings(CodeStyle.java:366)
```

This method seems to be new: https://github.com/JetBrains/intellij-community/commit/4275f5491d6c70b5d73b3286d563022e93344d1d
