### ISSUE TITLE
krasa.formatter.settings.ProjectSettingsComponent@7005f8c8: org/eclipse/jdt/core/formatter/CodeFormatter

### ISSUE THREAD

**Issue by mahboob-awan** [krasa/EclipseCodeFormatter#37]
OS: Ubuntu 14.04LTS
IntelliJ IDEA 14.0.3 (Community Edition)

Detail:>>>>>>>>>>>>>>>>>>>>>>

krasa.formatter.settings.ProjectSettingsComponent@7005f8c8: org/eclipse/jdt/core/formatter/CodeFormatter
java.lang.NoClassDefFoundError: org/eclipse/jdt/core/formatter/CodeFormatter
	at krasa.formatter.plugin.EclipseCodeStyleManager.<init>(EclipseCodeStyleManager.java:42)
	at krasa.formatter.plugin.ProjectCodeStyleInstaller.installCodeFormatter(ProjectCodeStyleInstaller.java:55)
	at krasa.formatter.plugin.ProjectCodeStyleInstaller.changeFormatterTo(ProjectCodeStyleInstaller.java:48)
	at krasa.formatter.settings.ProjectSettingsComponent.install(ProjectSettingsComponent.java:66)
	at krasa.formatter.settings.ProjectSettingsComponent.projectOpened(ProjectSettingsComponent.java:93)
	at com.intellij.openapi.project.impl.ProjectImpl.projectOpened(ProjectImpl.java:421)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:75)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:456)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$3.projectOpened(ProjectManagerImpl.java:157)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:930)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:442)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:544)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:181)
	at com.intellij.ide.RecentProjectsManager.doOpenProject(RecentProjectsManager.java:46)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:340)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:287)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
	at com.sun.proxy.$Proxy45.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication.loadProject(IdeaApplication.java:306)
	at com.intellij.idea.IdeaApplication.access$500(IdeaApplication.java:55)
	at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:280)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.core.formatter.CodeFormatter PluginClassLoader[EclipseCodeFormatter, 14.8.132.637]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more

**Comment by krasa** [comment]
have you tried reinstall of the plugin?
