### ISSUE TITLE
Throwable raised when formatting selected region in file.

### ISSUE THREAD

**Issue by artn** [krasa/EclipseCodeFormatter#40]
Below is event log from Intellij Idea 14.1, Using Eclipse Code Formatter 14.8.132.167, OSX 10.9.5

After this issue occurred, The file can not be edited. So I close and reopen it.

```
Negative start offset: (-32,-19); 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:222)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:214)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:210)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
	at com.intellij.openapi.util.ProperTextRange.<init>(ProperTextRange.java:25)
	at com.intellij.openapi.util.ProperTextRange.shiftRight(ProperTextRange.java:45)
	at com.intellij.openapi.util.ProperTextRange.shiftRight(ProperTextRange.java:23)
	at com.intellij.psi.formatter.common.InjectedLanguageBlockBuilder$1.visit(InjectedLanguageBlockBuilder.java:89)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:157)
	at com.intellij.psi.formatter.common.InjectedLanguageBlockBuilder.addInjectedBlocks(InjectedLanguageBlockBuilder.java:111)
	at com.intellij.psi.formatter.xml.AbstractXmlBlock.buildInjectedPsiBlocks(AbstractXmlBlock.java:434)
	at com.intellij.psi.formatter.xml.XmlTagBlock.processChild(XmlTagBlock.java:152)
	at com.intellij.psi.formatter.xml.XmlTagBlock.a(XmlTagBlock.java:183)
	at com.intellij.psi.formatter.xml.XmlTagBlock.a(XmlTagBlock.java:173)
	at com.intellij.psi.formatter.xml.XmlTagBlock.processChild(XmlTagBlock.java:150)
	at com.intellij.psi.formatter.xml.XmlTagBlock.buildChildren(XmlTagBlock.java:119)
	at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:60)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:177)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:236)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:110)
	at com.intellij.formatting.FormatProcessor$WrapBlocksState.doIteration(FormatProcessor.java:1335)
	at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1268)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:266)
	at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:515)
	at com.intellij.formatting.FormatterImpl.adjustLineIndent(FormatterImpl.java:448)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$5.doPerform(CodeStyleManagerImpl.java:363)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$5.doPerform(CodeStyleManagerImpl.java:360)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:106)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.a(CodeStyleManagerImpl.java:360)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.access$500(CodeStyleManagerImpl.java:60)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$3.compute(CodeStyleManagerImpl.java:323)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$3.compute(CodeStyleManagerImpl.java:320)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:121)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.adjustLineIndent(CodeStyleManagerImpl.java:320)
	at krasa.formatter.plugin.DelegatingCodeStyleManager.adjustLineIndent(DelegatingCodeStyleManager.java:86)
	at com.intellij.codeInsight.editorActions.EmacsStyleIndentAction$Handler.invoke(EmacsStyleIndentAction.java:81)
	at com.intellij.codeInsight.actions.CodeInsightAction$1$1.run(CodeInsightAction.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.codeInsight.actions.CodeInsightAction$1.run(CodeInsightAction.java:66)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:54)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:40)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by krasa** [comment]
Looks like IntelliJ bug. Please fill an issue here:  http://youtrack.jetbrains.net/issues/IDEA
