### ISSUE TITLE
com.intellij.diagnostic.PluginException in last update

### ISSUE THREAD

**Issue by rz-robsn** [krasa/EclipseCodeFormatter#52]
Hi,

I am using this plugin and since I updated to version 15.1.132.637.0, I systematically get a `PluginException` whenever we try to format a java file, the formatting failed too : 

	startOffset2226, endOffset:2787, length of file 5395: org/eclipse/jdt/internal/formatter/DefaultCodeFormatter : Unsupported major.minor version 51.0 [Plugin: EclipseCodeFormatter]
	com.intellij.diagnostic.PluginException: org/eclipse/jdt/internal/formatter/DefaultCodeFormatter : Unsupported major.minor version 51.0 [Plugin: EclipseCodeFormatter]
		at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
		at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
		at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
		at krasa.formatter.eclipse.JavaCodeFormatterFacade.newCodeFormatter(JavaCodeFormatterFacade.java:65)
		at krasa.formatter.eclipse.JavaCodeFormatterFacade.getCodeFormatter(JavaCodeFormatterFacade.java:47)
		at krasa.formatter.eclipse.JavaCodeFormatterFacade.format(JavaCodeFormatterFacade.java:148)
		at krasa.formatter.plugin.EclipseCodeFormatter.reformat(EclipseCodeFormatter.java:102)
		at krasa.formatter.plugin.EclipseCodeFormatter.formatWhenEditorIsOpen(EclipseCodeFormatter.java:83)
		at krasa.formatter.plugin.EclipseCodeFormatter.format(EclipseCodeFormatter.java:50)
		at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:203)
		at krasa.formatter.plugin.EclipseCodeStyleManager.format(EclipseCodeStyleManager.java:103)
		at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:67)
		at com.intellij.codeInsight.actions.ReformatCodeProcessor$1.call(ReformatCodeProcessor.java:128)
		at com.intellij.codeInsight.actions.ReformatCodeProcessor$1.call(ReformatCodeProcessor.java:113)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
		at java.util.concurrent.FutureTask.run(FutureTask.java:138)
		at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1$1.run(AbstractLayoutCodeProcessor.java:238)
		at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
		at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:235)
		at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:227)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
		at java.util.concurrent.FutureTask.run(FutureTask.java:138)
		at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$3.run(AbstractLayoutCodeProcessor.java:342)
		at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1$1.run(AbstractLayoutCodeProcessor.java:450)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
		at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1.run(AbstractLayoutCodeProcessor.java:445)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
		at java.awt.EventQueue.access$400(EventQueue.java:82)
		at java.awt.EventQueue$2.run(EventQueue.java:676)
		at java.awt.EventQueue$2.run(EventQueue.java:674)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
	Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/jdt/internal/formatter/DefaultCodeFormatter : Unsupported major.minor version 51.0
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
		at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
		at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
		at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
		at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
		... 46 more

I reproduced the issue on Android studio 1.22 and Android studio 1.3 RC 3.

If you need more information about my setup, don't hesitate to ask !

Thanks.

**Comment by krasa** [comment]
You are running on JRE 1.6 right? 

It seems that the new formatter needs 1.7, could you try to check **Use old Java formatter from Eclipse 4.4** in settings?

**Comment by rz-robsn** [comment]
> You are running on JRE 1.6 right ?

Yes, I own a mac and [Android Studio currently runs on JRE 6 for OS X](https://developer.android.com/sdk/index.html#Requirements).

I uninstalled version 15.1.132.637.0 and installed 14.9.132.637 instead. It works fine now.

Thanks for your help.

**Comment by krasa** [comment]
It should now work, could you please try it?

https://github.com/krasa/EclipseCodeFormatter/releases/download/15.1.132.637.1/EclipseFormatter.zip
- download and install it

**Comment by rz-robsn** [comment]
I installed and download the zipped file you provided and the formatter works fine, now. It also showed a "you're using the 4.4 formatter because you're on JRE 6" message popup when I formatted my file.

Many thanks to you guys.

**Comment by krasa** [comment]
Thank you!
