### ISSUE TITLE
IncorrectOperationException

### ISSUE THREAD

**Issue by markus-s24** [krasa/EclipseCodeFormatter#54]
Must not modify PSI inside save listener
com.intellij.util.IncorrectOperationException: Must not modify PSI inside save listener
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:138)
	at com.intellij.psi.impl.DocumentCommitProcessor$2.run(DocumentCommitProcessor.java:215)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$8.compute(CodeStyleManagerImpl.java:674)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:121)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$10.compute(CodeStyleManagerImpl.java:709)
	at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:894)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:705)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:671)
	at krasa.formatter.plugin.DelegatingCodeStyleManager.performActionWithFormatterDisabled(DelegatingCodeStyleManager.java:139)
	at com.intellij.psi.impl.DocumentCommitProcessor.doActualPsiChange(DocumentCommitProcessor.java:200)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:136)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:126)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:322)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:133)
	at com.intellij.psi.impl.PsiDocumentManagerBase$3.run(PsiDocumentManagerBase.java:292)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:289)
	at com.intellij.psi.impl.DocumentCommitThread$5.run(DocumentCommitThread.java:521)
	at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:417)
	at com.intellij.psi.impl.PsiDocumentManagerBase$5.run(PsiDocumentManagerBase.java:374)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.psi.impl.PsiDocumentManagerBase.doCommit(PsiDocumentManagerBase.java:366)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:278)
	at com.intellij.codeInsight.editorActions.XmlTagNameSynchronizer$TagNameSynchronizer.beforeDocumentChange(XmlTagNameSynchronizer.java:218)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:760)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:722)
	at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:528)
	at com.intellij.openapi.editor.impl.DocumentImpl$2.run(DocumentImpl.java:223)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.util.DocumentUtil$1.run(DocumentUtil.java:64)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:296)
	at com.intellij.util.DocumentUtil.writeInRunUndoTransparentAction(DocumentUtil.java:61)
	at com.intellij.openapi.editor.impl.DocumentImpl.stripTrailingSpaces(DocumentImpl.java:220)
	at com.intellij.openapi.editor.impl.TrailingSpacesStripper.stripIfNotCurrentLine(TrailingSpacesStripper.java:199)
	at com.intellij.openapi.editor.impl.TrailingSpacesStripper.a(TrailingSpacesStripper.java:80)
	at com.intellij.openapi.editor.impl.TrailingSpacesStripper.beforeDocumentSaving(TrailingSpacesStripper.java:60)
	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:159)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:87)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:116)
	at com.sun.proxy.$Proxy21.beforeDocumentSaving(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$4.run(FileDocumentManagerImpl.java:422)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:354)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:419)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:393)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:314)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:293)
	at org.jetbrains.plugins.terminal.JBTerminalPanel.focusGained(JBTerminalPanel.java:257)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:202)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:202)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:202)
	at java.awt.Component.processFocusEvent(Component.java:6303)
	at java.awt.Component.processEvent(Component.java:6170)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1856)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:911)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:523)
	at java.awt.Component.dispatchEventImpl(Component.java:4648)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by krasa** [comment]
IntelliJ bug, please use https://youtrack.jetbrains.com/
