### ISSUE TITLE
Attempt to modify PSI for non-committed Document!

### ISSUE THREAD

**Issue by bedla** [krasa/EclipseCodeFormatter#59]
Hi, I have used formatter for whole project containing 800 .java files and got following exception. IDEA version is  IntelliJ IDEA 14.1.4
Build #IU-141.1532, built on June 18, 2015
JRE: 1.8.0_51-b16 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Eclipse Import Optimizer failed: imports: import XXX;import java.math.BigInteger;, settings: [java, javax, org, com]
krasa.formatter.plugin.ImportSorterException: imports: import XXX;import java.math.BigInteger;, settings: [java, javax, org, com]
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:74)
	at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:18)
	at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:44)
	at com.intellij.codeInsight.actions.OptimizeImportsProcessor$1.run(OptimizeImportsProcessor.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1$1.run(AbstractLayoutCodeProcessor.java:238)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:235)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:227)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.a(AbstractLayoutCodeProcessor.java:553)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.access$800(AbstractLayoutCodeProcessor.java:485)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask$1.run(AbstractLayoutCodeProcessor.java:542)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.iteration(AbstractLayoutCodeProcessor.java:539)
	at com.intellij.util.SequentialModalProgressTask$1.run(SequentialModalProgressTask.java:95)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:818)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:633)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:363)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:293)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$4.run(AbstractLayoutCodeProcessor.java:371)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$6.run(AbstractLayoutCodeProcessor.java:390)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1$1.run(AbstractLayoutCodeProcessor.java:450)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1.run(AbstractLayoutCodeProcessor.java:445)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
	at com.intellij.pom.core.impl.PomModelImpl.b(PomModelImpl.java:308)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:143)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:165)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:707)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:204)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:552)
	at com.intellij.psi.impl.source.tree.java.JavaFileElement.replaceChildInternal(JavaFileElement.java:97)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:207)
	at com.intellij.psi.impl.source.JavaStubPsiElement.replace(JavaStubPsiElement.java:150)
	at krasa.formatter.plugin.ImportSorterAdapter.sortImports(ImportSorterAdapter.java:80)
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:57)
	... 58 more

krasa.formatter.plugin.ImportSorterException: imports: import XXX;import org.joda.time.DateTime;import org.junit.Before;import org.junit.Test;import org.mockito.Mock;import org.mockito.MockitoAnnotations;import javax.enterprise.inject.Instance;import java.math.BigDecimal;import java.math.BigInteger;import static org.junit.Assert.assertEquals;import static org.junit.Assert.assertNull;import static org.mockito.Mockito.when;, settings: [java, javax, org, com]
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:74)
	at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:18)
	at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:44)
	at com.intellij.codeInsight.actions.OptimizeImportsProcessor$1.run(OptimizeImportsProcessor.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1$1.run(AbstractLayoutCodeProcessor.java:238)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:235)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:227)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.a(AbstractLayoutCodeProcessor.java:553)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.access$800(AbstractLayoutCodeProcessor.java:485)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask$1.run(AbstractLayoutCodeProcessor.java:542)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.iteration(AbstractLayoutCodeProcessor.java:539)
	at com.intellij.util.SequentialModalProgressTask$1.run(SequentialModalProgressTask.java:95)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:818)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:633)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:363)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:293)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$4.run(AbstractLayoutCodeProcessor.java:371)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$6.run(AbstractLayoutCodeProcessor.java:390)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1$1.run(AbstractLayoutCodeProcessor.java:450)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1.run(AbstractLayoutCodeProcessor.java:445)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
	at com.intellij.pom.core.impl.PomModelImpl.b(PomModelImpl.java:308)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:143)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:165)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:707)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:204)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:552)
	at com.intellij.psi.impl.source.tree.java.JavaFileElement.replaceChildInternal(JavaFileElement.java:97)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:207)
	at com.intellij.psi.impl.source.JavaStubPsiElement.replace(JavaStubPsiElement.java:150)
	at krasa.formatter.plugin.ImportSorterAdapter.sortImports(ImportSorterAdapter.java:80)
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:57)
	... 58 more

**Comment by krasa** [comment]
Hi, 
I don't know how it could happen, but I have added another commit. Let me know if it happens again. Thanks.
