### ISSUE TITLE
Error in EclipseImportOptimizer.java

### ISSUE THREAD

**Issue by mogren** [krasa/EclipseCodeFormatter#67]
I first did format code, then optimize imports:

Idea Ultimate 14.1.4
Eclipse Formatter 15.2.132.637.2

```
invalid type of PsiLocalVariable:application of class class com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl, valid=true
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:380)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:351)
    at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:90)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.getType(PsiReferenceExpressionImpl.java:418)
    at com.intellij.psi.scope.util.PsiScopesUtil.setupAndRunProcessor(PsiScopesUtil.java:314)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.a(PsiReferenceExpressionImpl.java:286)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.a(PsiReferenceExpressionImpl.java:271)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:59)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:194)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:183)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:779)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:769)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:332)
    at com.intellij.psi.impl.source.codeStyle.ImportHelper$4.visitReferenceElement(ImportHelper.java:872)
    at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitReferenceExpression(JavaRecursiveElementWalkingVisitor.java:44)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:676)
    at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:64)
    at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:26)
    at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
    at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
    at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:73)
    at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:34)
    at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:56)
    at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:470)
    at com.intellij.psi.impl.source.codeStyle.ImportHelper.a(ImportHelper.java:867)
    at com.intellij.psi.impl.source.codeStyle.ImportHelper.a(ImportHelper.java:728)
    at com.intellij.psi.impl.source.codeStyle.ImportHelper.prepareOptimizeImportsResult(ImportHelper.java:76)
    at com.intellij.psi.impl.source.codeStyle.JavaCodeStyleManagerImpl.prepareOptimizeImportsResult(JavaCodeStyleManagerImpl.java:123)
    at com.intellij.lang.java.JavaImportOptimizer.processFile(JavaImportOptimizer.java:46)
    at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:43)
    at com.intellij.codeInsight.actions.OptimizeImportsProcessor$1.run(OptimizeImportsProcessor.java:96)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1$1.run(AbstractLayoutCodeProcessor.java:238)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:235)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:227)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$3.run(AbstractLayoutCodeProcessor.java:342)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1$1.run(AbstractLayoutCodeProcessor.java:450)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1.run(AbstractLayoutCodeProcessor.java:445)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by krasa** [comment]
Looks like IntelliJ bug, but I will make a change to make sure.

**Comment by mogren** [comment]
Thanks, I'll let you know if it happens again or if I can create a reproducible test case.
