### ISSUE TITLE
Interfaces indented incorrectly

### ISSUE THREAD

**Issue by wallacms** [krasa/EclipseCodeFormatter#78]
I'm using Mars 4.5.1 and IntelliJ 15.  I've been running tests where I reformat my whole code base in Eclipse and then reformat the whole thing in IntelliJ using the EclipseFormatter plugin.  My hope is that nothing would change but I'm seeing inconsistencies in the formatting of interfaces.

I have the formatter setup to use mixed tabs and spaces.  In Eclipse, method declarations in interfaces are properly indented using tabs.  In IntelliJ the tabs are converted to spaces.  Attached below is my formatter configuration.

[formatter.txt](https://github.com/krasa/EclipseCodeFormatter/files/37928/formatter.txt)

**Comment by wallacms** [comment]
Perhaps this is an upstream bug? https://bugs.eclipse.org/bugs/show_bug.cgi?id=471364

**Comment by krasa** [comment]
working on updating Eclipse libs now...

**Comment by krasa** [comment]
so i tried to refactor those libs into more add-ons... 
```
[  60663]  ERROR - ns.AbstractLayoutCodeProcessor - java.util.concurrent.ExecutionException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher.newCodeFormatter()Lkrasa/formatter/common/eclipse/JavaCodeFormatter; @23: putfield
  Reason:
    Type 'krasa/formatter/eclipse44/JavaCodeFormatter44' (current frame, stack[1]) is not assignable to 'krasa/formatter/common/eclipse/JavaCodeFormatter'
  Current Frame:
    bci: @23
    flags: { }
    locals: { 'krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher' }
    stack: { 'krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher', 'krasa/formatter/eclipse44/JavaCodeFormatter44' }
  Bytecode:
    0x0000000: 2ab4 0003 9900 192a bb00 0759 2ab4 0002
    0x0000010: 2ab4 0004 b700 08b5 0005 a700 3b12 09b8
    0x0000020: 000a 9900 192a bb00 0b59 2ab4 0002 2ab4
    0x0000030: 0004 b700 0cb5 0005 a700 1d2a bb00 0759
    0x0000040: 2ab4 0002 2ab4 0004 b700 08b5 0005 2ab4
    0x0000050: 0004 b800 0da7 000d 4cbb 000f 592b b700
    0x0000060: 10bf 2ab4 0005 b0                      
  Exception Handler Table:
    bci [0, 85] => handler: 88
  Stackmap Table:
    same_frame(@29)
    same_frame(@59)
    same_frame(@85)
    same_locals_1_stack_item_frame(@88,Object[#50])
    same_frame(@98)
 
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher.newCodeFormatter()Lkrasa/formatter/common/eclipse/JavaCodeFormatter; @23: putfield
  Reason:
    Type 'krasa/formatter/eclipse44/JavaCodeFormatter44' (current frame, stack[1]) is not assignable to 'krasa/formatter/common/eclipse/JavaCodeFormatter'
  Current Frame:
    bci: @23
    flags: { }
    locals: { 'krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher' }
    stack: { 'krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher', 'krasa/formatter/eclipse44/JavaCodeFormatter44' }
  Bytecode:
    0x0000000: 2ab4 0003 9900 192a bb00 0759 2ab4 0002
    0x0000010: 2ab4 0004 b700 08b5 0005 a700 3b12 09b8
    0x0000020: 000a 9900 192a bb00 0b59 2ab4 0002 2ab4
    0x0000030: 0004 b700 0cb5 0005 a700 1d2a bb00 0759
    0x0000040: 2ab4 0002 2ab4 0004 b700 08b5 0005 2ab4
    0x0000050: 0004 b800 0da7 000d 4cbb 000f 592b b700
    0x0000060: 10bf 2ab4 0005 b0                      
  Exception Handler Table:
    bci [0, 85] => handler: 88
  Stackmap Table:
    same_frame(@29)
    same_frame(@59)
    same_frame(@85)
    same_locals_1_stack_item_frame(@88,Object[#50])
    same_frame(@98)

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$3.run(AbstractLayoutCodeProcessor.java:347)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1$1.run(AbstractLayoutCodeProcessor.java:460)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$8$1.run(AbstractLayoutCodeProcessor.java:455)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:335)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:392)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher.newCodeFormatter()Lkrasa/formatter/common/eclipse/JavaCodeFormatter; @23: putfield
  Reason:
    Type 'krasa/formatter/eclipse44/JavaCodeFormatter44' (current frame, stack[1]) is not assignable to 'krasa/formatter/common/eclipse/JavaCodeFormatter'
  Current Frame:
    bci: @23
    flags: { }
    locals: { 'krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher' }
    stack: { 'krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher', 'krasa/formatter/eclipse44/JavaCodeFormatter44' }
  Bytecode:
    0x0000000: 2ab4 0003 9900 192a bb00 0759 2ab4 0002
    0x0000010: 2ab4 0004 b700 08b5 0005 a700 3b12 09b8
    0x0000020: 000a 9900 192a bb00 0b59 2ab4 0002 2ab4
    0x0000030: 0004 b700 0cb5 0005 a700 1d2a bb00 0759
    0x0000040: 2ab4 0002 2ab4 0004 b700 08b5 0005 2ab4
    0x0000050: 0004 b800 0da7 000d 4cbb 000f 592b b700
    0x0000060: 10bf 2ab4 0005 b0                      
  Exception Handler Table:
    bci [0, 85] => handler: 88
  Stackmap Table:
    same_frame(@29)
    same_frame(@59)
    same_frame(@85)
    same_locals_1_stack_item_frame(@88,Object[#50])
    same_frame(@98)

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:243)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$3.run(AbstractLayoutCodeProcessor.java:345)
	... 24 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher.newCodeFormatter()Lkrasa/formatter/common/eclipse/JavaCodeFormatter; @23: putfield
  Reason:
    Type 'krasa/formatter/eclipse44/JavaCodeFormatter44' (current frame, stack[1]) is not assignable to 'krasa/formatter/common/eclipse/JavaCodeFormatter'
  Current Frame:
    bci: @23
    flags: { }
    locals: { 'krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher' }
    stack: { 'krasa/formatter/core/eclipse/JavaCodeFormatterDispatcher', 'krasa/formatter/eclipse44/JavaCodeFormatter44' }
  Bytecode:
    0x0000000: 2ab4 0003 9900 192a bb00 0759 2ab4 0002
    0x0000010: 2ab4 0004 b700 08b5 0005 a700 3b12 09b8
    0x0000020: 000a 9900 192a bb00 0b59 2ab4 0002 2ab4
    0x0000030: 0004 b700 0cb5 0005 a700 1d2a bb00 0759
    0x0000040: 2ab4 0002 2ab4 0004 b700 08b5 0005 2ab4
    0x0000050: 0004 b800 0da7 000d 4cbb 000f 592b b700
    0x0000060: 10bf 2ab4 0005 b0                      
  Exception Handler Table:
    bci [0, 85] => handler: 88
  Stackmap Table:
    same_frame(@29)
    same_frame(@59)
    same_frame(@85)
    same_locals_1_stack_item_frame(@88,Object[#50])
    same_frame(@98)

	at krasa.formatter.core.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:209)
	at krasa.formatter.core.plugin.EclipseCodeStyleManager.format(EclipseCodeStyleManager.java:109)
	at krasa.formatter.core.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:72)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor$1.call(ReformatCodeProcessor.java:133)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor$1.call(ReformatCodeProcessor.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1$1.run(AbstractLayoutCodeProcessor.java:239)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:975)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:236)
	... 27 more
[  60763]  ERROR - ns.AbstractLayoutCodeProcessor - IntelliJ IDEA (Community Edition) IC-142.2670.3  Build #IC-142.2670.3 
[  60764]  ERROR - ns.AbstractLayoutCodeProcessor - JDK: 1.8.0_51 
[  60764]  ERROR - ns.AbstractLayoutCodeProcessor - VM: Java HotSpot(TM) 64-Bit Server VM 
[  60764]  ERROR - ns.AbstractLayoutCodeProcessor - Vendor: Oracle Corporation 
[  60764]  ERROR - ns.AbstractLayoutCodeProcessor - OS: Windows 7 
[  60764]  ERROR - ns.AbstractLayoutCodeProcessor - Last Action: ReformatCode 
[  60764]  ERROR - ns.AbstractLayoutCodeProcessor - Current Command: Reformat Code 
```
:+1:

**Comment by wallacms** [comment]
That seems like it's expecting JavaCodeFormatter44 to implement/extend JavaCodeFormatter, though I'm not sure why it's not being caught by the compiler.  Can you commit the code in question to a branch?

**Comment by krasa** [comment]
Yep, I have put an Interface in a shared library, which is bundled in each plugin. IJ then loads it separately for each of three plugins using different classloaders, and it is therefore incompatible. 

I think that making an Extension Point coud solve this, or reflection.

**Comment by krasa** [comment]
You can try it, if you install the plugin manually: https://github.com/krasa/EclipseCodeFormatter/releases/download/15.3/EclipseFormatter.zip

**Comment by wallacms** [comment]
Nice! I will try it out tonight.

Thanks,

Matt
