### ISSUE TITLE
RuntimeException: Document is locked by write PSI operations. Use PsiD

### ISSUE THREAD

**Issue by dancioca** [krasa/EclipseCodeFormatter#81]
```
IdeaLoggingEvent[message=Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document., throwable=java.lang.RuntimeException: Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document.

 at com.intellij.psi.impl.source.PostprocessReformattingAspect.beforeDocumentChanged(PostprocessReformattingAspect.java:284)
 at com.intellij.psi.impl.PsiDocumentManagerImpl.beforeDocumentChangeOnUnlockedDocument(PsiDocumentManagerImpl.java:124)
 at com.intellij.psi.impl.PsiDocumentManagerBase.beforeDocumentChange(PsiDocumentManagerBase.java:636)
 at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
 at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
 at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
 at com.sun.proxy.$Proxy22.beforeDocumentChange(Unknown Source)
 at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:760)
 at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:722)
 at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:607)
 at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:560)
 at com.intellij.psi.formatter.DocumentBasedFormattingModel.replaceWhiteSpace(DocumentBasedFormattingModel.java:158)
 at com.intellij.formatting.FormatProcessor.a(FormatProcessor.java:414)
 at com.intellij.formatting.FormatProcessor.access$2700(FormatProcessor.java:42)
 at com.intellij.formatting.FormatProcessor$ApplyChangesState.doIteration(FormatProcessor.java:1440)
 at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1266)
 at com.intellij.formatting.FormatProcessor.a(FormatProcessor.java:329)
 at com.intellij.formatting.FormatProcessor.performModifications(FormatProcessor.java:316)
 at com.intellij.formatting.FormatProcessor.performModifications(FormatProcessor.java:305)
 at com.intellij.formatting.FormatterImpl.adjustLineIndentsForRange(FormatterImpl.java:382)
 at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$6.doPerform(CodeStyleManagerImpl.java:383)
 at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:109)
 at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.adjustLineIndent(CodeStyleManagerImpl.java:380)
 at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatNewlyAddedElement(CodeStyleManagerImpl.java:314)
 at krasa.formatter.plugin.DelegatingCodeStyleManager.reformatNewlyAddedElement(DelegatingCodeStyleManager.java:116)
 at com.intellij.lang.javascript.refactoring.introduce.JSBaseIntroduceHandler.fixFormat(JSBaseIntroduceHandler.java:775)
 at com.intellij.lang.javascript.refactoring.introduce.JSBaseIntroduceHandler.doRefactoring(JSBaseIntroduceHandler.java:755)
 at com.intellij.lang.javascript.refactoring.introduce.JSBaseInplaceIntroducer$1.compute(JSBaseInplaceIntroducer.java:75)
 at com.intellij.lang.javascript.refactoring.introduce.JSBaseInplaceIntroducer$1.compute(JSBaseInplaceIntroducer.java:72)
 at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:943)
 at com.intellij.lang.javascript.refactoring.introduce.JSBaseInplaceIntroducer.createFieldToStartTemplateOn(JSBaseInplaceIntroducer.java:71)
 at com.intellij.lang.javascript.refactoring.introduce.JSBaseInplaceIntroducer.createFieldToStartTemplateOn(JSBaseInplaceIntroducer.java:32)
 at com.intellij.refactoring.introduce.inplace.AbstractInplaceIntroducer$2.run(AbstractInplaceIntroducer.java:218)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
 at com.intellij.refactoring.introduce.inplace.AbstractInplaceIntroducer.startInplaceIntroduceTemplate(AbstractInplaceIntroducer.java:214)
 at com.intellij.lang.javascript.refactoring.introduce.JSBaseIntroduceHandler$1.pass(JSBaseIntroduceHandler.java:321)
 at com.intellij.lang.javascript.refactoring.introduce.JSBaseIntroduceHandler$1.pass(JSBaseIntroduceHandler.java:306)
 at com.intellij.refactoring.introduce.inplace.OccurrencesChooser$5.run(OccurrencesChooser.java:146)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by krasa** [comment]
IntelliJ bug, report at https://youtrack.jetbrains.com/issues/IDEA
