### ISSUE TITLE
You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions ?

### ISSUE THREAD

**Issue by yanyinxi** [krasa/EclipseCodeFormatter#83]
Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
	at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:38)
	at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:19)
	at krasa.formatter.settings.provider.CachedProvider.get(CachedProvider.java:26)
	at krasa.formatter.plugin.EclipseImportOptimizer.getImportSorter(EclipseImportOptimizer.java:97)
	at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:60)
	at krasa.formatter.plugin.EclipseImportOptimizer.access$100(EclipseImportOptimizer.java:22)
	at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:48)
	at com.intellij.codeInsight.actions.OptimizeImportsProcessor$1.run(OptimizeImportsProcessor.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1$1.run(AbstractLayoutCodeProcessor.java:237)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:234)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$1.call(AbstractLayoutCodeProcessor.java:226)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.runWithoutProgress(AbstractLayoutCodeProcessor.java:490)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.b(AddImportAction.java:254)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.access$300(AddImportAction.java:56)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction$4$1$1.run(AddImportAction.java:223)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:254)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction$4$1.run(AddImportAction.java:220)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction$4.run(AddImportAction.java:217)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.a(AddImportAction.java:214)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.access$200(AddImportAction.java:56)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction$1.onChosen(AddImportAction.java:120)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction$1.onChosen(AddImportAction.java:101)
	at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:382)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:337)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:250)
	at com.intellij.ui.popup.WizardPopup.a(WizardPopup.java:366)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:346)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:121)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:146)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:74)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:599)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

IDEA 15.0.2  报这个错误！请问怎么解决？

**Comment by yanyinxi** [comment]
@krasa   @danmidwood   @hrchu   感谢！

**Comment by krasa** [comment]
please upload the file

**Comment by yanyinxi** [comment]
[Uploading Formatter.txt…]()



@krasa   Help look! Thank

**Comment by krasa** [comment]
You did not upload anything, closing.

**Comment by iusofts** [comment]
请问解决了吗？我也遇到了同样问题

**Comment by krasa** [comment]
English?
