### ISSUE TITLE
Crash on formatting some files

### ISSUE THREAD

**Issue by dvovney** [krasa/EclipseCodeFormatter#9]
on formatting some file idea crashes. can't understand why. please fix it. it's really annoying!
my system is kubuntu. idea version 13.0.1, plugin version: 13.0.1.1. This crash was with older versions of plugin and older versions of idea (12.x)

 stack trace:

Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
    at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:38)
    at krasa.formatter.settings.provider.ImportOrderProvider.readFile(ImportOrderProvider.java:19)
    at krasa.formatter.settings.provider.CachedProvider.get(CachedProvider.java:26)
    at krasa.formatter.plugin.EclipseImportOptimizer.getImportSorter(EclipseImportOptimizer.java:112)
    at krasa.formatter.plugin.EclipseImportOptimizer.optimizeImportsByEclipse(EclipseImportOptimizer.java:87)
    at krasa.formatter.plugin.EclipseImportOptimizer.process(EclipseImportOptimizer.java:62)
    at krasa.formatter.plugin.EclipseImportOptimizer.access$000(EclipseImportOptimizer.java:28)
    at krasa.formatter.plugin.EclipseImportOptimizer$1.run(EclipseImportOptimizer.java:46)
    at com.intellij.codeInsight.actions.OptimizeImportsProcessor$1.run(OptimizeImportsProcessor.java:80)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at com.intellij.codeInsight.actions.ReformatAndOptimizeImportsProcessor$1.call(ReformatAndOptimizeImportsProcessor.java:90)
    at com.intellij.codeInsight.actions.ReformatAndOptimizeImportsProcessor$1.call(ReformatAndOptimizeImportsProcessor.java:80)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$2.run(AbstractLayoutCodeProcessor.java:210)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:997)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$9$1$1.run(AbstractLayoutCodeProcessor.java:489)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
    at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$9$1.run(AbstractLayoutCodeProcessor.java:484)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:346)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by zhaozhxcn** [comment]
Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.

**Comment by zhaozhxcn** [comment]
Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.

**Comment by zhaozhxcn** [comment]
Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.

**Comment by zhaozhxcn** [comment]
Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.

**Comment by zhaozhxcn** [comment]
Eclipse Import Optimizer failed: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.
krasa.formatter.exception.ParsingFailedException: You must provide either *.importorder file or 'org.eclipse.jdt.ui.prefs' file, see instructions.

**Comment by zhongliangjun1** [comment]
step1: 
find the org.eclipse.jdt.ui.prefs file under your eclipse workspace ( /workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs )

step2:
copy it to another space

step3:
add "org.eclipse.jdt.ui.importorder=java;javax;org;com;" to it

step4:
set your Import order  from the org.eclipse.jdt.ui.prefs file which you adjust just now.

**Comment by zhongliangjun1** [comment]
- Check "Optimizing Imports" configuration
  	- Set import order
  	  - Either leave the default
  	  - Or set path to Eclipse configuration file:
    		-  Go to Eclise | Windows | Preferences | Java | Code Style | Organize Imports
    			- Either click on "Export...", ([example](https://github.com/krasa/EclipseCodeFormatter/blob/master/test/resources/bcjur2.importorder))
    			- Or enable project specific settings and **use "org.eclipse.jdt.ui.prefs" file which should contain the line "org.eclipse.jdt.ui.importorder=..."**
  	- Value of "Class count to use import with '*'" and "Name count to use static import with '*'" (Settings |  Editor | Code Style | Imports) - Eclipse uses value of 30 by default
  	- For versions lower than 4.0 - make sure to keep disabled IntelliJ's Import Optimizing in the reformat dialog (Settings | Editor | Show "Reformat Code" dialog), the plugin will take care of imports anyway
  	- For versions higher than 4.0 - imports will be reordered together with normal IntelliJ's import optimizing
  	- **Disable "Optimize imports on the fly"**
