### ISSUE TITLE
"Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core"

### ISSUE THREAD

**Issue by philipp-classen** [krasa/EclipseCodeFormatter#98]
"mvn verify" fails with the following error message (on the current master state cdea7bfbac235e978e3337008c595038f9157b5c). It fails to resolve jdt-core:

```
phil@lin-classenp:~/github/formatter-maven-plugin (master)$ mvn verify
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 10 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 10 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] Computing target platform for MavenProject: net.revelc.code.formatter:jdt-core:1.6.0-SNAPSHOT @ /home/phil/github/formatter-maven-plugin/formatters/jdt-core/pom.xml
[INFO] Resolving dependencies of MavenProject: net.revelc.code.formatter:jdt-core:1.6.0-SNAPSHOT @ /home/phil/github/formatter-maven-plugin/formatters/jdt-core/pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: jdt-core 1.6.0.qualifier
[ERROR]   Missing requirement: jdt-core 1.6.0.qualifier requires 'bundle org.eclipse.jdt.core [1.0.0,10.0.0)' but it could not be found
[ERROR] 
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.]
	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
	at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:166)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:103)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies(P2DependencyResolver.java:352)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies(P2DependencyResolver.java:325)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:107)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	... 11 more
```

("maven verify" against the "formatter-maven-plugin-0.5.2" tag works.)

**Comment by philipp-classen** [comment]
Sorry, pasted into the wrong project. Please ignore it. :-(
